### PR TITLE
Release/0.1.0

### PR DESCRIPTION
**Pull request by JustinAiken**
Think this is about ready to be released and used now...

@benlangfeld and @crienzo take a look when you have a moment...pending your review I'll do the initial release, push the gem, and switch this repo to use Git Flow for further development...

### CODE REVIEW

**Comment by benlangfeld** [comment]
I don't agree that the tone detector gets any value from being an actor. Can you justify that?

**Comment by JustinAiken** [comment]
If I tried to call '#after' on the 'Call' object (or any other actor), the timer never fired, and post-hangup there'd be lots of Celluoid warnings about terminating timers.

**Comment by JustinAiken** [comment]
Here's a reproduction of why I can't just do `call.after {...}`:

``` ruby
require 'adhearsion'

class A
  include Celluloid
end

class B
  def go(foo)
    foo.after(3) { puts "I've waited long enough" }
    puts "waiting..."
  end
end

B.new.go A.new
sleep 5

# -> waiting...
# -> I've waited long enough

B.new.go Adhearsion::Call.new
sleep 5

# -> waiting...
# nothing else, it's done
```

**Comment by benlangfeld** [comment]
That's a bug, please provide a repo. This shouldn't be an actor, and even if it should, you're never shutting it down ;)

**Comment by JustinAiken** [comment]
Now that https://github.com/adhearsion/adhearsion/issues/431 is fixed, I added a commit to end ToneDetector's acting career.

**Comment by benlangfeld** [comment]
:+1:

**Pull request merged**
